## Homework 1

Answers for the **Homework 1** of the ML Zoomcamp 2026.

### Q1. Pandas version

What version of Pandas did you install?

In [1]:
import numpy as np
import pandas as pd
pd.__version__

'3.0.5'

### Getting the data

For this homework, the dataset used is the 2026 Car Fuel Efficiency dataset. It is available [here](https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv).

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Q2. Records count

How many records are in the dataset?

In [3]:
df.shape

(10000, 11)

### Q3. Fuel types

How many fuel types are presented in the dataset?

In [4]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

### Q4. Missing values

How many columns in the dataset have missing values?

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

### Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [6]:
df[df["origin"]=="Asia"]["fuel_efficiency_mpg"].describe()

count    2994.000000
mean       30.741015
std         2.835474
min        21.300000
25%        28.700000
50%        30.700000
75%        32.500000
max        41.200000
Name: fuel_efficiency_mpg, dtype: float64

### Q6. Median value of horsepower

1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed?
- **Yes, it decreased**

In [7]:
# 1. Find the median value of the horsepower column in the dataset.
print(df["horsepower"].median())

254.0

In [8]:
df["horsepower"].describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [9]:
# 2. Next, calculate the most frequent value of the same horsepower column.
print(df["horsepower"].mode()[0])

252.0

In [10]:
df["horsepower"].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [11]:
# 3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value 
# from the previous step.
df_horsepower_mostf = df.copy()
df_horsepower_mostf["horsepower"] = df_horsepower_mostf["horsepower"].fillna(252)

In [12]:
# 4. Now, calculate the median value of horsepower once again.
print(df_horsepower_mostf["horsepower"].median())

252.0

In [13]:
df_horsepower_mostf["horsepower"].describe()

count    10000.000000
mean       254.231500
std         21.830757
min        171.000000
25%        241.000000
50%        252.000000
75%        268.000000
max        334.000000
Name: horsepower, dtype: float64

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [14]:
# 1. Select all the cars from Asia
df_filter = df[df["origin"]=="Asia"]

In [15]:
# 2. Select only columns vehicle_weight and model_year
df_filter = df_filter[["vehicle_weight", "model_year"]]

In [16]:
# 3. Select the first 7 values
df_filter = df_filter.iloc[:7]
df_filter

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [17]:
# 4. Get the underlying NumPy array. Let's call it X
X = df_filter[["vehicle_weight", "model_year"]].to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [18]:
# 5. Compute matrix-matrix multiplication between the transpose of X and X.
# To get the transpose, use X.T. Let's call the result XTX.
XTX = np.matmul(X.transpose(), X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [19]:
# 6. Invert XTX.
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [20]:
# 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [21]:
# 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = np.matmul(np.matmul(inv_XTX, np.transpose(X)), y)
w

array([0.13644777, 0.2327492 ])

In [22]:
# 9. What's the sum of all the elements of the result?
print(w[0] + w[1])

0.36919696904925486